### ISSUE TITLE
Re-design Form

### ISSUE THREAD

**Issue by lopezpedres** [lopezpedres/crochet-front#1]
### Overview
It's a UI/UX good practice to keep displaying the form's input name when selected, a placeholder should not replace the name of the input

## Todo
- [x] Redesign the form in Figma
- [x] Apply changes and create a PR
- [x] If more issues created related to this issue related parents issue's number 
- [x] Change color of the form as a container so it can highlight more
