### ISSUE TITLE
Add date to form object body

### ISSUE THREAD

**Issue by lopezpedres** [lopezpedres/crochet-front#10]
## Overview 

The object that is received in Firebase does not contain any date or id needed to organize the documents within each collection

## Todo

- [ ] Add a date form for the object body
- [ ] Modify the collections format in Firebase
- [ ] Test and organize the documents by date
