### ISSUE TITLE
Create productPage

### ISSUE THREAD

**Issue by lopezpedres** [lopezpedres/crochet-front#7]
### Overview
Create productPage for each product using dinamic routing with Nextjs

## Todo

- [x] Create  productPage.tsx
- [x] Create a products mock data in Firebase
- [x] Retrive products and use the products name to build the routes for each product
